In [206]:
import numpy as np
i = np.array([[1,3,20],[9,15,14]])
info_a = np.mat(i)
#秘钥
k = np.array([[1,0,1],[3,2,7],[1,9,2]])
info_b = np.mat(k)

#信息加密c
c=info_a*info_b
print(c)
print(c*info_b.I)


[[ 30 186  62]
 [ 68 156 142]]
[[ 1.  3. 20.]
 [ 9. 15. 14.]]


In [102]:
def commpression(string):
    new_str=''
    count=0
    temp=string[0]
    for i in range(0,len(string)):
        if temp==string[i]:
            count+=1
        else:
            new_str=new_str+str(temp)+str(count)
            count=1
            temp=string[i]
        if i == len(string)-1:
            new_str=new_str+str(temp)+str(count)  
    return new_str

print(commpression('aaaaacccccdddddddbbbbbqqqq'))

a5c5d7b5q4


In [104]:
from itertools import groupby

In [117]:
def decompression(string):
    new_str=''
    string_list = [''.join(list(k)) for g,k in groupby(string,key=lambda x:x.isalpha())]
    for i in range(0,len(string_list)):
        if i%2 == 1:
            new_str=new_str+string_list[i-1]*int(string_list[i])
    return new_str
        
    

In [119]:
decompression('a10b26c7e6')

1
3
5
7


'aaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbccccccceeeeee'

In [126]:
dict={i:chr(i) for i in range(97,123)}

In [127]:
dict

{97: 'a',
 98: 'b',
 99: 'c',
 100: 'd',
 101: 'e',
 102: 'f',
 103: 'g',
 104: 'h',
 105: 'i',
 106: 'j',
 107: 'k',
 108: 'l',
 109: 'm',
 110: 'n',
 111: 'o',
 112: 'p',
 113: 'q',
 114: 'r',
 115: 's',
 116: 't',
 117: 'u',
 118: 'v',
 119: 'w',
 120: 'x',
 121: 'y',
 122: 'z'}

['✐',
 '✑',
 '✒',
 '✓',
 '✔',
 '✕',
 '✖',
 '✗',
 '✘',
 '✙',
 '✚',
 '✛',
 '✜',
 '✝',
 '✞',
 '✟',
 '✠',
 '✡',
 '✢',
 '✣',
 '✤',
 '✥',
 '✦',
 '✧',
 '✨',
 '✩',
 '✪',
 '✫',
 '✬',
 '✭',
 '✮',
 '✯',
 '✰',
 '✱',
 '✲',
 '✳',
 '✴',
 '✵',
 '✶',
 '✷',
 '✸',
 '✹',
 '✺',
 '✻',
 '✼',
 '✽',
 '✾',
 '✿',
 '❀',
 '❁',
 '❂',
 '❃',
 '❄',
 '❅',
 '❆',
 '❇',
 '❈',
 '❉',
 '❊',
 '❋',
 '❌',
 '❍',
 '❎',
 '❏',
 '❐',
 '❑',
 '❒',
 '❓',
 '❔',
 '❕',
 '❖',
 '❗',
 '❘',
 '❙',
 '❚',
 '❛',
 '❜',
 '❝',
 '❞',
 '❟',
 '❠',
 '❡',
 '❢',
 '❣',
 '❤',
 '❥',
 '❦',
 '❧',
 '❨',
 '❩',
 '❪',
 '❫',
 '❬',
 '❭',
 '❮',
 '❯',
 '❰',
 '❱',
 '❲',
 '❳',
 '❴',
 '❵',
 '❶',
 '❷',
 '❸',
 '❹',
 '❺',
 '❻',
 '❼',
 '❽',
 '❾',
 '❿',
 '➀',
 '➁',
 '➂',
 '➃',
 '➄',
 '➅',
 '➆',
 '➇',
 '➈',
 '➉',
 '➊',
 '➋',
 '➌',
 '➍',
 '➎',
 '➏',
 '➐',
 '➑',
 '➒',
 '➓',
 '➔',
 '➕',
 '➖',
 '➗',
 '➘',
 '➙',
 '➚',
 '➛',
 '➜',
 '➝',
 '➞',
 '➟',
 '➠',
 '➡',
 '➢',
 '➣',
 '➤',
 '➥',
 '➦',
 '➧',
 '➨',
 '➩',
 '➪',
 '➫',
 '➬',
 '➭',
 '➮',
 '➯',
 '➰',
 '➱',
 '➲',
 '➳',
 '➴',
 '➵',
 '➶'

In [141]:
def is_chinese(uchar):         
    if '\u4e00' <= uchar<='\u9fff':
        return True
    else:
        return False
is_chinese('1')


False

In [222]:
j=[i for i in range(0,9)]
print(j)
j.remove(j[2])
j

[0, 1, 2, 3, 4, 5, 6, 7, 8]


[0, 1, 3, 4, 5, 6, 7, 8]

In [220]:
k=[[j.pop(0) for i in range(int(len(j)/3))] for i in range(3)]

[0, 1, 2]

In [205]:
import numpy as np

info = np.array([[1,3,9],
                 [14,15,20]])
info_A = np.mat(info)   #使用 mat 方法将 2 维数组转化为矩阵

key = np.array([[3,5,7],
                [4,7,20],
                [100,0,0]])
key_A = np.mat(key)   #使用 mat 方法将 2 维数组转化为矩阵
print("密钥：",key_A)
after_A = info_A*key_A
print("加密后：",after_A)
print("#######################")
print("解密")
key1 = np.array([[3,5,7],
                [4,7,20],
                [100,0,0]])
key1_A = np.mat(key1)   #使用 mat 方法将 2 维数组转化为矩阵
print(after_A*key1_A.I)

密钥： [[  3   5   7]
 [  4   7  20]
 [100   0   0]]
加密后： [[ 915   26   67]
 [2102  175  398]]
#######################
解密
[[ 1.  3.  9.]
 [14. 15. 20.]]


'我'

97